name: Unit tests

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      - name: Install modules
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Execute unit tests
        run: npm run test:ci
