name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: EAS build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Backend URL
        run: sed -i -e 's,http://10.0.2.2:8000,${{ secrets.BACKEND_URL }},g' app.json

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Update Expo
        run: expo update

      - name: Publish build
        run: eas build --platform android --profile preview --non-interactive
